version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: summarizer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paradise@108
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/summarizer_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: paradise@108
    depends_on:
      - db
