apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: {{ .Values.fastapi.image }}
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  selector:
    app: fastapi
  ports:
    - port: 8001
      targetPort: 8001
