/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.springframework.boot") version "3.1.0"
    id ("io.spring.dependency-management") version "1.1.0"
    java
}

group = "org.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_21

repositories {
    mavenCentral()
}


dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.postgresql:postgresql")
    implementation(fileTree("libs") { include("*.jar") })
    implementation("org.scala-lang:scala-library:2.13.10")
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.postgresql:postgresql")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}

tasks.test {
    useJUnitPlatform()
}